"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 19:52:28.541807
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_data_sources_name'))
    )
    op.create_table('drill_holes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=False),
    sa.Column('mn_pct', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drill_holes')),
    sa.UniqueConstraint('code', name=op.f('uq_drill_holes_code'))
    )
    op.create_table('mines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('daily_target_t', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mines')),
    sa.UniqueConstraint('name', name=op.f('uq_mines_name'))
    )
    op.create_table('reserve_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_key', sa.String(length=12), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('tonnage_t', sa.Float(), nullable=False),
    sa.Column('grade_mn_pct', sa.Float(), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=False),
    sa.Column('holes_nearby', sa.Integer(), nullable=False),
    sa.Column('nearest_mine_km', sa.Float(), nullable=False),
    sa.Column('drill_suggested', sa.Boolean(), nullable=False),
    sa.Column('drill_recommended', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reserve_zones'))
    )
    with op.batch_alter_table('reserve_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserve_zones_cell_key'), ['cell_key'], unique=True)

    op.create_table('satellite_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=8), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('cell_deg', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_satellite_cells'))
    )
    with op.batch_alter_table('satellite_cells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_satellite_cells_indicator'), ['indicator'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_ok', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('rows_warning', sa.Integer(), nullable=False),
    sa.Column('issues_total', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('blast_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('bench', sa.String(length=40), nullable=False),
    sa.Column('blast_date', sa.Date(), nullable=False),
    sa.Column('planned_t', sa.Float(), nullable=False),
    sa.Column('actual_t', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('delay_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_blast_plans_mine_id_mines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blast_plans'))
    )
    with op.batch_alter_table('blast_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blast_plans_blast_date'), ['blast_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_blast_plans_mine_id'), ['mine_id'], unique=False)

    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_data_quality_issues_upload_id_uploads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_issues'))
    )
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_issues_upload_id'), ['upload_id'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('downtime_hrs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_equipment_mine_id_mines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('code', name=op.f('uq_equipment_code'))
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_mine_id'), ['mine_id'], unique=False)

    op.create_table('production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('planned_t', sa.Float(), nullable=False),
    sa.Column('actual_t', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_production_records_mine_id_mines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_records'))
    )
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.create_index('ix_prod_mine_date', ['mine_id', 'day'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('risk_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_risk_owners_assigned_by_users')),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_risk_owners_mine_id_mines')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_owners_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_owners')),
    sa.UniqueConstraint('mine_id', name=op.f('uq_risk_owners_mine_id'))
    )
    op.create_table('shortfall_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('expected_shortfall_t', sa.Float(), nullable=False),
    sa.Column('main_cause', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_shortfall_risks_mine_id_mines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortfall_risks'))
    )
    with op.batch_alter_table('shortfall_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shortfall_risks_mine_id'), ['mine_id'], unique=False)

    op.create_table('stockpile_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('closing_t', sa.Float(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_stockpile_readings_mine_id_mines')),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_stockpile_readings_upload_id_uploads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stockpile_readings')),
    sa.UniqueConstraint('mine_id', 'day', name='uq_stockpile_mine_day')
    )
    with op.batch_alter_table('stockpile_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stockpile_readings_mine_id'), ['mine_id'], unique=False)

    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('rain_mm', sa.Float(), nullable=False),
    sa.Column('wind_kmh', sa.Float(), nullable=False),
    sa.Column('blasting', sa.String(length=12), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_weather_forecasts_mine_id_mines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_forecasts'))
    )
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_forecasts_mine_id'), ['mine_id'], unique=False)

    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('wind_kmh', sa.Float(), nullable=False),
    sa.Column('rain_now_mm', sa.Float(), nullable=False),
    sa.Column('rain_today_mm', sa.Float(), nullable=False),
    sa.Column('blasting', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_weather_observations_mine_id_mines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observations'))
    )
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_observations_mine_id'), ['mine_id'], unique=False)

    op.create_table('action_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recovery_t', sa.Float(), nullable=False),
    sa.Column('cost_inr_lakh', sa.Float(), nullable=False),
    sa.Column('feasibility', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['shortfall_risks.id'], name=op.f('fk_action_recommendations_risk_id_shortfall_risks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_recommendations'))
    )
    with op.batch_alter_table('action_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_recommendations_risk_id'), ['risk_id'], unique=False)

    op.create_table('equipment_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('downtime_hrs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_snapshots_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_equipment_snapshots_upload_id_uploads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_snapshots'))
    )
    with op.batch_alter_table('equipment_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_snapshots_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_snapshots_taken_at'), ['taken_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_snapshots_upload_id'), ['upload_id'], unique=False)

    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['shortfall_risks.id'], name=op.f('fk_risk_factors_risk_id_shortfall_risks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_factors'))
    )
    with op.batch_alter_table('risk_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_factors_risk_id'), ['risk_id'], unique=False)

    op.create_table('action_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action_recommendations.id'], name=op.f('fk_action_comments_action_id_action_recommendations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_action_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_comments'))
    )
    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_comments_action_id'), ['action_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_comments_action_id'))

    op.drop_table('action_comments')
    with op.batch_alter_table('risk_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_factors_risk_id'))

    op.drop_table('risk_factors')
    with op.batch_alter_table('equipment_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_snapshots_upload_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_snapshots_taken_at'))
        batch_op.drop_index(batch_op.f('ix_equipment_snapshots_equipment_id'))

    op.drop_table('equipment_snapshots')
    with op.batch_alter_table('action_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_recommendations_risk_id'))

    op.drop_table('action_recommendations')
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_observations_mine_id'))

    op.drop_table('weather_observations')
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_forecasts_mine_id'))

    op.drop_table('weather_forecasts')
    with op.batch_alter_table('stockpile_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stockpile_readings_mine_id'))

    op.drop_table('stockpile_readings')
    with op.batch_alter_table('shortfall_risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shortfall_risks_mine_id'))

    op.drop_table('shortfall_risks')
    op.drop_table('risk_owners')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.drop_index('ix_prod_mine_date')

    op.drop_table('production_records')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_mine_id'))

    op.drop_table('equipment')
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_upload_id'))

    op.drop_table('data_quality_issues')
    with op.batch_alter_table('blast_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blast_plans_mine_id'))
        batch_op.drop_index(batch_op.f('ix_blast_plans_blast_date'))

    op.drop_table('blast_plans')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('uploads')
    with op.batch_alter_table('satellite_cells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satellite_cells_indicator'))

    op.drop_table('satellite_cells')
    with op.batch_alter_table('reserve_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserve_zones_cell_key'))

    op.drop_table('reserve_zones')
    op.drop_table('mines')
    op.drop_table('drill_holes')
    op.drop_table('data_sources')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
